SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RASPROFILEPRICES](
	[ORIGREC] [int] IDENTITY(2,1) NOT NULL,
	[DESIREDTAT] [nvarchar](10) NULL,
	[ORIGSTS] [nchar](1) NOT NULL,
	[PREPPRICE] [numeric](8, 2) NULL,
	[PRICE] [numeric](8, 2) NULL,
	[PRICELISTID] [nvarchar](15) NOT NULL,
	[PRICELISTVERSION] [int] NOT NULL,
	[PROFILE] [nvarchar](71) NOT NULL,
	[SP_CODE] [int] NOT NULL,
	[TAX] [int] NULL,
 CONSTRAINT [RASPROFILEPRICES_PK] PRIMARY KEY CLUSTERED 
(
	[PRICELISTID] ASC,
	[PRICELISTVERSION] ASC,
	[SP_CODE] ASC,
	[PROFILE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RASPROFILEPRICES] ADD  CONSTRAINT [df_RASPROFILEPRICES_ORIGSTS]  DEFAULT (N'N') FOR [ORIGSTS]
GO
ALTER TABLE [dbo].[RASPROFILEPRICES]  WITH CHECK ADD  CONSTRAINT [RASPROFILEPRICES_FK1] FOREIGN KEY([PRICELISTID], [PRICELISTVERSION])
REFERENCES [dbo].[RASPRICELIST] ([PRICELISTID], [PRICELISTVERSION])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[RASPROFILEPRICES] CHECK CONSTRAINT [RASPROFILEPRICES_FK1]
GO
