SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RASPRICELIST](
	[ORIGREC] [int] IDENTITY(9,1) NOT NULL,
	[APPROVEDAT] [datetime] NULL,
	[APPROVEDBY] [nvarchar](15) NULL,
	[CREATED_BY] [nvarchar](15) NULL,
	[DEFAULTRICELIST] [nvarchar](2) NULL,
	[DESIREDTAT] [nvarchar](10) NULL,
	[EXPDATE] [datetime] NULL,
	[ORIGSTS] [nchar](1) NOT NULL,
	[PRICELISTDESC] [nvarchar](50) NULL,
	[PRICELISTID] [nvarchar](15) NOT NULL,
	[PRICELISTTYPE] [nvarchar](10) NULL,
	[PRICELISTVERSION] [int] NOT NULL,
	[RETIREDBY] [nvarchar](15) NULL,
	[RETIREDDAT] [datetime] NULL,
	[STARTDDATE] [datetime] NULL,
	[STATUS] [nvarchar](10) NULL,
 CONSTRAINT [RASPRICELIST_PK] PRIMARY KEY CLUSTERED 
(
	[PRICELISTID] ASC,
	[PRICELISTVERSION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [IX_RASPRICELIST_PRICELISTID_STATUS] ON [dbo].[RASPRICELIST]
(
	[PRICELISTID] ASC,
	[STATUS] ASC
)
INCLUDE([PRICELISTVERSION]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RASPRICELIST] ADD  CONSTRAINT [df_RASPRICELIST_ORIGSTS]  DEFAULT (N'N') FOR [ORIGSTS]
GO
