SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RASTESTPRICES](
	[ORIGREC] [int] IDENTITY(103,1) NOT NULL,
	[CANBEPARTIALTEST] [nvarchar](2) NULL,
	[DEFAULTP] [nvarchar](1) NULL,
	[DESIREDTAT] [nvarchar](10) NULL,
	[ORIGSTS] [nchar](1) NOT NULL,
	[PREPPRICE] [numeric](8, 2) NULL,
	[PRICE] [numeric](8, 2) NULL,
	[PRICELISTID] [nvarchar](15) NOT NULL,
	[PRICELISTVERSION] [int] NOT NULL,
	[SP_CODE] [int] NOT NULL,
	[TAX] [int] NULL,
	[TESTCODE] [int] NOT NULL,
	[LABTIME] [int] NULL,
	[INSTTIME] [int] NULL,
 CONSTRAINT [RASTESTPRICES_PK] PRIMARY KEY CLUSTERED 
(
	[PRICELISTID] ASC,
	[PRICELISTVERSION] ASC,
	[SP_CODE] ASC,
	[TESTCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [IX_RASTESTPRICES_LOOKUP] ON [dbo].[RASTESTPRICES]
(
	[PRICELISTID] ASC,
	[TESTCODE] ASC,
	[PRICELISTVERSION] ASC
)
INCLUDE([PRICE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [IX_RASTESTPRICES_LOOKUP_INCL] ON [dbo].[RASTESTPRICES]
(
	[PRICELISTID] ASC,
	[TESTCODE] ASC,
	[PRICELISTVERSION] ASC
)
INCLUDE([PRICE]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RASTESTPRICES] ADD  CONSTRAINT [df_RASTESTPRICES_ORIGSTS]  DEFAULT (N'N') FOR [ORIGSTS]
GO
ALTER TABLE [dbo].[RASTESTPRICES]  WITH CHECK ADD  CONSTRAINT [RASTESTPRICES_FK1] FOREIGN KEY([PRICELISTID], [PRICELISTVERSION])
REFERENCES [dbo].[RASPRICELIST] ([PRICELISTID], [PRICELISTVERSION])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[RASTESTPRICES] CHECK CONSTRAINT [RASTESTPRICES_FK1]
GO
